name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -j4

    - name: run tests
      run: |
        cd build
        ctest -VV
